# Generated by Django 2.1.7 on 2019-09-18 21:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('imagestore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='parent_album',
        ),
        migrations.AddField(
            model_name='album',
            name='level',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='lft',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalbums', to=settings.IMAGESTORE_ALBUM_MODEL, verbose_name='Parent Album'),
        ),
        migrations.AddField(
            model_name='album',
            name='rght',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='album',
            name='tree_id',
            field=models.PositiveIntegerField(db_index=True, default=0, editable=False),
            preserve_default=False,
        ),
    ]
