# Generated by Django 2.1.7 on 2019-03-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagestore', '0003_auto_20190219_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='summary',
            field=models.TextField(blank=True, null=True, verbose_name='Summary'),
        ),
    ]
