# Generated by Django 2.1.7 on 2019-03-26 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imagestore', '0004_image_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='tripreport',
            field=models.TextField(blank=True, null=True, verbose_name='Trip Report'),
        ),
    ]
