# Generated by Django 2.1.7 on 2019-03-27 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imagestore', '0005_album_tripreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subalbums', to=settings.IMAGESTORE_ALBUM_MODEL, verbose_name='Parent Album'),
        ),
    ]
