# Generated by Django 2.1.7 on 2019-03-27 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imagestore', '0006_album_album'),
    ]

    operations = [
        migrations.RenameField(
            model_name='album',
            old_name='album',
            new_name='parent_album',
        ),
    ]
